#!/bin/bash

if [ $# -lt 2 ]
then
  echo "Usage: $0 <project> <where (e.g. snapshots or releases)>"
  exit 1
fi

# PROJECT SHOULD BE 
PROJECT=$1
# WHERE SHOULD BE 'releases' or 'snapshots'
WHERE=$2

MVNREPO=/Users/tombocklisch/Documents/ScalableMinds/scalableminds.github.com

sbt "project $PROJECT" 'set organization:="com.scalableminds"' clean publish-local

cp -rv ~/.ivy2/local/com.scalableminds/$PROJECT* $MVNREPO/$WHERE/com.scalableminds/

cd $MVNREPO
git pull origin master
git add $WHERE/com.scalableminds
git ci -m "updated $PROJECT"
git push origin master